"""initial migration

Revision ID: 5132b4ee7ff
Revises: None
Create Date: 2016-07-16 22:32:45.012691

"""

# revision identifiers, used by Alembic.
revision = '5132b4ee7ff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
